### PR TITLE
Potential fix for issue #17

### PR DESCRIPTION
**Pull request by Prospero100**
Hi Jason,

I made a bit of a mess of the commit comments unfortunately (said 'true' when I meant 'false'!), but the basic changes here are to remove the parameter for "ReflectionOnly" on the assembly loading in the plugin deployer tool. The method parameter had a default value of "false" but all the calling code passed in "true". 

This (I think) is what caused a problem for any ILMerged plugin assemblies. The "ReflectionOnly = true" in the assembly container meant that the bundled types could not be found during reflection leading to a Could not load file or assembly IO exception. There may be other ways to pipe the referenced assembiles in, but it looked like a convoluted pathway. 

So I've instead stripped out the parameter from the method signature and hard coded ReflectionOnly= **false** in the method body. I've tested deploying both ILMerged plugin dlls and unmerged ones too... both work fine now.

Please review the changes and if acceptable to you, pull into the master. Keep up the good work :)

Cheers,
Paul

### CODE REVIEW

**Comment by jlattimer** [comment]
When I'm testing I'm see that the .pdb file is being locked after the first publish, preventing me from publishing a second time. This was part of the reason I came up with the solution I did that diverged from Scott's original code, except at the time it was the .dll being locked. We'll need to dig into this some more.

**Comment by Prospero100** [comment]
Thanks Jason - it's a difficult area (for me at least) - the assembly loading and unloading. I've been having a google around, most message boards recommend using a separate app domain and using a DoCallBack delegate to prevent the locking, but I can see from the code that this is exactly the case here (`containerAppDomain `in _AssemblyContainer.cs_). 

I can confirm (when using the code in this branch) that after an initial plugin deployment I then get a locked file error against the pdb file, whenever I try to compile the plugin project. 

I'll try have another look at this later in the week, but so far I'm drawing a blank.

**Comment by jlattimer** [comment]
So it turns out that it appears that this behavior only surfaced during debugging the extension. If actually installed it appears to work just fine. This is good, but still raises the issue that debugging going forward would be an issue.

**Comment by Prospero100** [comment]
That's not so bad then, a bit of a pain when debugging around that area, but probably liveable with 🙂

Sent from my Windows 10 phone

________________________________

**Comment by jlattimer** [comment]
I have to look into it more next week when I have time. It's really going to limit debugging as it effects both deployment types. It's slow enough debugging when you need to spin up a new VS instance as it is, but needing to restart after each deploy is to clear the block would be a huge time killer.

**Pull request merged**
