### PR TITLE
Made the extension compat with vs2019 and changed templates to 4.6.2

### PR DESCRIPTION
**Pull request by brendon-colburn**
Hey Jason,

Today I went through and updated your extension so that it can work with vs2019 and so that the project templates work with Dynamics version 9... However the changes are breaking for earlier versions of dynamics or visual studio.  I was wondering if you wanted to create a branch that this could be merged into so that people can leverage it when needed?

### CODE REVIEW

**Comment by pete-mc** [comment]
Hey Brendon, do you have a complied .vsix file you have working that you could publish?

**Comment by jlattimer** [comment]
@brendon-colburn How exactly is it breaking earlier versions?

**Comment by jlattimer** [comment]
Is it because the baseline .NET version is 4.6.2 when it needs to be 4.5.2 for on-premise / pre-9.0.2.9 SDK?

**Comment by brendon-colburn** [comment]
> Is it because the baseline .NET version is 4.6.2 when it needs to be 4.5.2 for on-premise / pre-9.0.2.9 SDK?

Yup, that's the reason.  As everyone is aware, Microsoft is pushing pretty hard with our One Version and getting everyone into the cloud.  I suppose that since you have previous releases available on here @jlattimer that it is no harm no foul.  To @pete-mc 's request, can we have this recompiled and added into the releases area for people that don't have visual studio to build the vsix themselves?  Thanks for the prompt merge regardless.

**Comment by jlattimer** [comment]
I re-worked what you had and got it so that it should force a minimum of 4.6.2 or above when using targeting the latest SDK versions otherwise 4.5.2.

I'll try and push an update to the marketplace in the next day or so.

**Pull request merged**
